name: OpenFL
markdown: RedcarpetCustom
redcarpet:
  extensions: ["strikethrough", "no_intra_emphasis", "autolink", "tables", "with_toc_data", "fenced_code_blocks"]
highlighter: pygments
excerpt_separator: "<!--more-->"
paginate: 5
paginate_path: "blog/page/:num"
url: http://www.openfl.org
navigation:
- title: Showcase
  url: /showcase/
- title: Blog
  url: /blog/
- title: Learn
  url: /learn/
#- title: Community
#  url: http://community.openfl.org
permalink: /blog/:year/:month/:day/:title
rss_path: /blog/
rss_post_limit: 10
