name: OpenFL
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "no_intra_emphasis", "autolink"]
highlighter: pygments
excerpt_separator: "<!--more-->"
paginate: 5
paginate_path: "blog/page/:num"
url: http://www.openfl.org
navigation:
- title: Blog
  url: /blog/
- title: Showcase
  url: /showcase/
- title: Documentation
  url: /documentation/
#- title: Community
#  url: http://community.openfl.org
permalink: /blog/:year/:month/:day/:title
rss_path: /blog/
rss_post_limit: 10
