name: OpenFL
collections:
  showcase:
    output: true
    permalink: /showcase/title/:path/
defaults:
 - scope:
     path: ""
     type: showcase
   values:
     layout: showcase-item
 - scope:
     path: "showcase"
   values:
     layout: showcase
 - scope:
     path: ""
     type: posts
   values:
     layout: post
 - scope:
     path: "learn"
   values:
     layout: learn-sidebar
 - scope:
     path: "lime"
   values:
     layout: default-sidebar-lime
excerpt_separator: "<!--more-->"
plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-redirect-from
 - redcarpet
 - pygments
highlighter: pygments
markdown: Redcarpet
paginate: 6
paginate_path: "blog/page/:num"
permalink: /blog/:year/:month/:day/:title/
redcarpet:
  extensions: 
   - strikethrough
   - no_intra_emphasis
   - autolink
   - tables
   - with_toc_data
   - fenced_code_blocks
feed:
  path: blog/rss.xml
url: http://www.openfl.org