name: OpenFL
markdown: redcarpet
pygments: true
url: "/_site"
excerpt_separator: "<!--more-->"
paginate: 5
paginate_path: "blog/page/:num"
navigation:
- title: Blog
  url: /blog/
- title: Showcase
  url: /showcase/
- title: Docs
  url: /documentation/
- title: Forums
  url: /forums/
permalink: /:year/:month/:day/:title
