name: OpenFL
collections:
  showcase:
    output: true
    permalink: /showcase/title/:path/
defaults:
 - scope:
     path: ""
     type: showcase
   values:
     layout: showcase-item
 - scope:
     path: "showcase"
   values:
     layout: showcase
 - scope:
     path: ""
     type: posts
   values:
     layout: post
 - scope:
     path: "learn"
   values:
     layout: default-sidebar
excerpt_separator: "<!--more-->"
gems:
 - jekyll-paginate
 - redcarpet
 - pygments
highlighter: pygments
markdown: RedcarpetCustom
paginate: 6
paginate_path: "blog/page/:num"
permalink: /blog/:year/:month/:day/:title/
redcarpet:
  extensions: 
   - strikethrough
   - no_intra_emphasis
   - autolink
   - tables
   - with_toc_data
   - fenced_code_blocks
rss_path: /blog/
rss_post_limit: 10
url: http://www.openfl.org