version: 2
jobs:
  build:
    docker:
      - image: openfl/openfl.org-build:0.0.3
    steps:
      - checkout
      - run:
          name: Additional setup
          command: bundle install 
      - run:
          name: Build site
          command: bundle exec jekyll build
      - deploy:
          name: Deploy (if on master)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync _site s3://openfl --delete --acl bucket-owner-full-control --acl public-read
            else
              echo "Not on master (skipping step)"
            fi
